[project]
name = "gdb2geojson"
version = "0.1.0"
description = "Convert multiple Geodatabases to GeoJSON"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.1.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.6",
]
